# Generated by script/packaging.sh from the checksums v0.6.0 publishes.
class Docket < Formula
  desc "Git and Obsidian as one task tracker: a task is a Markdown file"
  homepage "https://github.com/didenkolab/docket"
  version "0.6.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/didenkolab/docket/releases/download/v0.6.0/docket_v0.6.0_darwin_arm64.tar.gz"
      sha256 "a66d6a463f2e4acbd065d6880b7a2b7d14452c44100731e3c8987b11fe6c5b91"
    end
    on_intel do
      url "https://github.com/didenkolab/docket/releases/download/v0.6.0/docket_v0.6.0_darwin_amd64.tar.gz"
      sha256 "4fa805997fb370836c8fc07695be406da4888ec1c9036a819b6efc78bd959993"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/didenkolab/docket/releases/download/v0.6.0/docket_v0.6.0_linux_arm64.tar.gz"
      sha256 "55af8f5d27f69b1ed78952513be4405e43e7d80ff02cb2505fd8c84d4fb530ba"
    end
    on_intel do
      url "https://github.com/didenkolab/docket/releases/download/v0.6.0/docket_v0.6.0_linux_amd64.tar.gz"
      sha256 "c7de1ab9ef2e41cb5316e00bb28c9c96b8588736bd93cc165fd9d4e02b4e918c"
    end
  end

  def install
    bin.install "docket"
  end

  test do
    assert_match "v0.6.0", shell_output("#{bin}/docket --version")
  end
end
